services:
  postgres:
    image: postgres
    container_name: pg_bikestore_db
    restart: always
    environment:
      POSTGRES_USER: admin    
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bikestore_db
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql/01-schema:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

volumes:
  postgres_data:
