services:
  postgres:
    image: postgres
    container_name: pg_integrated_db
    environment:
      POSTGRES_USER: root    
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: integrated_db
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - '5432:5432'

volumes:
  postgres_data:
