services:
  postgres:
    image: postgres
    container_name: pg_integrated_db
    restart: always
    environment:
      POSTGRES_USER: admin    
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: integrated_db
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql/schema:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

volumes:
  postgres_data:
